trigger:
- none   # adjust branch name if needed

pool:
  name: Default
  demands:
    - agent.name -equals playwright-agent

steps:
# Step 1: Use Node.js 18
- task: NodeTool@0
  displayName: 'Use Node.js 18'
  inputs:
    versionSpec: '18.x'

# Step 2: Clean workspace (only node_modules, keep package-lock.json)
- script: |
    rm -rf node_modules
    npm cache clean --force
  displayName: 'Clean workspace'

# Step 3: Install dependencies using lockfile
- script: |
    npm ci || npm install
  displayName: 'Install dependencies'

# Step 4: Install Playwright browsers
- script: |
    npx playwright install
  displayName: 'Install Playwright Browsers'

# # Step 5A: Run Regression suite
# - script: |
#     npm run cucumber-regression
#   displayName: 'Run Regression Tests'

# Step 5B: Run Validations suite
- script: |
    npm run cucumber-validations
  displayName: 'Run Validations Tests'

# Step 6: Publish reports (if generated in /reports folder)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'reports'
    artifactName: 'cucumber-reports'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Reports'